### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by tannerwelsh**
Thanks for requesting a review @pporche87 :). I left suggestions and warnings as inline comments and (in some cases) direct changes to the code.

### CODE REVIEW

**Comment by pporche87** [comment]
Thanks for the review @tannerwelsh! Super Helpful. 

Do you think we could get together regarding maybe a few ways to test these functions. I think I'll need some help on that after I make a few changes. 

Or even approach that as a topic of group discussion. 

Would be super helpful!

**Comment by tannerwelsh** [comment]
@pporche87 sure! Maybe a live coding session on "Testing the Command Line Todos"? I could schedule one for today or early next week.

**Comment by pporche87** [comment]
@tannerwelsh That would be awesome! I think it would help a lot of people.

**Comment by tannerwelsh** [comment]
Mkay let me see what I can pull together :)

Would you mind if I used your code as a starting point?

**Comment by pporche87** [comment]
That would be great!

**Pull request closed without merging**
